### ISSUE TITLE
Running on CPU only machine produces error: libcudart.so.10.1: No such file or directory

### ISSUE THREAD

**Issue by MarlNox** [YadiraF/DECA#18]
Hello everybody, 
When i try to run the script in my own laptop on CPU i get the following error message: 
```
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 25, in <module>
    from decalib.deca import DECA
  File "/home/ubuntu/DECA/decalib/deca.py", line 27, in <module>
    from .utils.renderer import SRenderY
  File "/home/ubuntu/DECA/decalib/utils/renderer.py", line 23, in <module>
    from pytorch3d.io import load_obj
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch3d/io/__init__.py", line 4, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch3d/io/obj_io.py", line 14, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
```
I own a machine which does not have a GPU, running it on Colab with a CPU only setting works without any issues though. 
Any ideas on how to fix it?

**Comment by SMassalski** [comment]
Hi,

Building pytorch and pytorch3d from source might help according to this thread [https://github.com/facebookresearch/pytorch3d/issues/339](url).
