### ISSUE TITLE
I get this error while working with deca  raise AttributeError(name) from None AttributeError: _2D

### ISSUE THREAD

**Issue by anushka17agarwal** [YadiraF/DECA#192]
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 131, in <module>
    main(parser.parse_args())
  File "demos/demo_reconstruct.py", line 40, in main
    testdata = datasets.TestData(args.inputpath, iscrop=args.iscrop, face_detector=args.detector, sample_step=args.sample_step)
  File "/home/YOTTAVDI/neuralgarage3/anushka/DECA/decalib/datasets/datasets.py", line 71, in __init__
    self.face_detector = detectors.FAN()
  File "/home/YOTTAVDI/neuralgarage3/anushka/DECA/decalib/datasets/detectors.py", line 22, in __init__
    self.model = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
  File "/home/YOTTAVDI/neuralgarage3/anaconda3/envs/deca-env/lib/python3.7/enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by xuduo18311199384** [comment]
Maybe can use 'self.model = face_alignment.FaceAlignment(1, flip_input=False)' instead

**Comment by koolou** [comment]
self.model = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False)
