### ISSUE TITLE
get error datasets/detectors.py", line 28 name 'image' is not defined

### ISSUE THREAD

**Issue by koolou** [YadiraF/DECA#196]
![WX20230803-015152@2x](https://github.com/yfeng95/DECA/assets/349998/90acf8b6-5a1e-43b4-bc24-76e97948a57b)
Traceback (most recent call last):
  File "/Users/loc/DECA/demos/demo_reconstruct.py", line 131, in <module>
    main(parser.parse_args())
  File "/Users/loc/DECA/demos/demo_reconstruct.py", line 40, in main
    testdata = datasets.TestData(args.inputpath, iscrop=args.iscrop, face_detector=args.detector, sample_step=args.sample_step)
  File "/Users/loc/DECA/decalib/datasets/datasets.py", line 71, in __init__
    self.face_detector = detectors.FAN()
  File "/Users/loc/DECA/decalib/datasets/detectors.py", line 28, in __init__
    out = self.model.get_landmarks(image)
--------------------
How should I set this "image" value?
I get an error when I directly use the content from the comments.

**Comment by xuduo18311199384** [comment]
![2023-08-03 09-10-08 的屏幕截图](https://github.com/yfeng95/DECA/assets/30895764/4a591113-3bff-481a-9ea6-b8049b28b0ba)
