### ISSUE TITLE
No module named 'pytorch3d.structures'

### ISSUE THREAD

**Issue by Garv62003** [YadiraF/DECA#221]
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
creating the FLAME Decoder
trained model found. load /content/drive/MyDrive/DECA/data/deca_model.tar
Traceback (most recent call last):
  File "/content/drive/MyDrive/DECA/demos/demo_reconstruct.py", line 131, in <module>
    main(parser.parse_args())
  File "/content/drive/MyDrive/DECA/demos/demo_reconstruct.py", line 46, in main
    deca = DECA(config = deca_cfg, device=device)
  File "/content/drive/MyDrive/DECA/decalib/deca.py", line 50, in __init__
    self._setup_renderer(self.cfg.model)
  File "/content/drive/MyDrive/DECA/decalib/deca.py", line 53, in _setup_renderer
    set_rasterizer(self.cfg.rasterizer_type)
  File "/content/drive/MyDrive/DECA/decalib/utils/renderer.py", line 27, in set_rasterizer
    from pytorch3d.structures import Meshes
ModuleNotFoundError: No module named 'pytorch3d.structures'

Please, can someone help me solve this issue?

**Comment by gokselmarufoglu** [comment]
hey man i have the same issue rn, did you managed to solve it? If you solved it can you share how did you solve it?
