### ISSUE TITLE
Issue while executing on a mac

### ISSUE THREAD

**Issue by NGWorld** [YadiraF/DECA#34]
While executing on a mac i got this error, can you help?

`Siddharths-MBP:DECA siddharthjha$ python demos/demo_reconstruct.py --help
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 25, in <module>
    from decalib.deca import DECA
  File "/Users/siddharthjha/Desktop/codebase/Facial reconstruction/DECA/decalib/deca.py", line 27, in <module>
    from .utils.renderer import SRenderY
  File "/Users/siddharthjha/Desktop/codebase/Facial reconstruction/DECA/decalib/utils/renderer.py", line 23, in <module>
    from pytorch3d.io import load_obj
  File "/Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/pytorch3d/io/__init__.py", line 4, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/pytorch3d/io/obj_io.py", line 16, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: dlopen(/Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so, 2): Symbol not found: __ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE
  Referenced from: /Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so
  Expected in: /Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/torch/lib/libc10.dylib
 in /Users/siddharthjha/.pyenv/versions/3.7.9/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so`

**Comment by zw20045500** [comment]
me too, do you fixed it?
