### ISSUE TITLE
About error

### ISSUE THREAD

**Issue by jarleon98** [YadiraF/DECA#59]
Hi, I'm learning face rebuilding now, when I run the demo, I have met some question which I don't know how to deal.So,can you help me? I have install all the enviroment the DECA need.AND the following is the error message:

  warnings.warn(f"Mtl file does not exist: {f_mtl}")
  0%|                                                                                            | 0/9 [00:00<?, ?it/s]TypeError: expected dtype object, got 'numpy.dtype[float32]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 105, in <module>
    main(parser.parse_args())
  File "demos/demo_reconstruct.py", line 44, in main
    name = testdata[i]['imagename']
  File "J:\face_rebuilding\DECA-master\decalib\datasets\datasets.py", line 119, in __getitem__
    bbox, bbox_type = self.face_detector.run(image)
  File "J:\face_rebuilding\DECA-master\decalib\datasets\detectors.py", line 29, in run
    out = self.model.get_landmarks(image)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\face_alignment\api.py", line 109, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces, return_bboxes)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\face_alignment\api.py", line 154, in get_landmarks_from_image
    pts, pts_img = get_preds_fromhm(out, center.numpy(), scale)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\face_alignment\utils.py", line 199, in get_preds_fromhm
    preds, preds_orig = _get_preds_fromhm(hm, idx, center, scale)
SystemError: CPUDispatcher(<function _get_preds_fromhm at 0x000002845BA877B8>) returned a result with an error set

I AM looking forward to your reply, THX!

**Comment by tanshuai0219** [comment]
same issue
