### ISSUE TITLE
ModuleNotFoundError: No module named 'iopath'

### ISSUE THREAD

**Issue by Michaelwhite34** [YadiraF/DECA#9]
My system is Ubuntu 20.04 LTS.I only omit usage 1.c. I get error when I try to run "python demos/demo_reconstruct.py -i TestSamples/examples --saveDepth True --saveObj True"

The message is 
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 25, in <module>
    from decalib.deca import DECA
  File "/home/michael/Downloads/DECA-master/decalib/deca.py", line 27, in <module>
    from .utils.renderer import SRenderY
  File "/home/michael/Downloads/DECA-master/decalib/utils/renderer.py", line 23, in <module>
    from pytorch3d.io import load_obj
  File "/home/michael/anaconda3/envs/DECA/lib/python3.7/site-packages/pytorch3d/io/__init__.py", line 4, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/home/michael/anaconda3/envs/DECA/lib/python3.7/site-packages/pytorch3d/io/obj_io.py", line 12, in <module>
    from pytorch3d.io.mtl_io import load_mtl, make_mesh_texture_atlas
  File "/home/michael/anaconda3/envs/DECA/lib/python3.7/site-packages/pytorch3d/io/mtl_io.py", line 11, in <module>
    from pytorch3d.io.utils import _open_file, _read_image
  File "/home/michael/anaconda3/envs/DECA/lib/python3.7/site-packages/pytorch3d/io/utils.py", line 10, in <module>
    from fvcore.common.file_io import PathManager
  File "/home/michael/anaconda3/envs/DECA/lib/python3.7/site-packages/fvcore/common/file_io.py", line 10, in <module>
    from iopath.common.file_io import (
ModuleNotFoundError: No module named 'iopath'

**Comment by Michaelwhite34** [comment]
Pip install fvcore solved this.

**Comment by Michaelwhite34** [comment]
..fc.weight  not available in reconstructed resnet
fc.bias  not available in reconstructed resnet

Is that a problem?

**Comment by tommy3266** [comment]
greate

**Comment by YadiraF** [comment]
> Pip install fvcore solved this.

Thanks for this, just added it to the requirement.
