### ISSUE TITLE
hang up while loading deca_model

### ISSUE THREAD

**Issue by bambi1202** [YadiraF/DECA#91]
My terminal hanged up while loading the given deca_model. deca.py line 88.
I think it is not processing anything task.
`trained model found. load D:\gitdoc\DECA\data\deca_model.tar`
Have anyone happened to this?
Please let me know if you have any solutions.

**Comment by bxiong97** [comment]
I am having the same issue. I'm using Windows 10, Visual Studio Code, Powershell to run the code. I already installed all those requirements successfully. 
I can also load deca_model.tar
However, I got an error message regarding the compiler version... I wonder why? Could anyone help with that? Many thanks! 

```
creating the FLAME Decoder
trained model found. load D:\Research\Face Reconstruction\DECA\DECA\data\deca_model.tar
C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 127, in <module>
    main(parser.parse_args())
  File "demos/demo_reconstruct.py", line 46, in main
    deca = DECA(config = deca_cfg, device=device)
  File "D:\Research\Face Reconstruction\DECA\DECA\decalib\deca.py", line 50, in __init__
    self._setup_renderer(self.cfg.model)
  File "D:\Research\Face Reconstruction\DECA\DECA\decalib\deca.py", line 53, in _setup_renderer
    set_rasterizer(self.cfg.rasterizer_type)
  File "D:\Research\Face Reconstruction\DECA\DECA\decalib\utils\renderer.py", line 41, in set_rasterizer
    extra_cuda_cflags = ['-std=c++14', '-ccbin=$$(which gcc-7)']) # cuda10.2 is not compatible with gcc9. Specify gcc 7
  File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 974, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1179, in _jit_compile 
    with_cuda=with_cuda)
  File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1272, in _write_ninja_file_and_build_library
    with_cuda=with_cuda)
  File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1645, in _write_ninja_file_to_build_library
    with_cuda=with_cuda)
  File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1747, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "C:\Users\Beibei\.conda\envs\py36\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\Beibei\.conda\envs\py36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
```

**Comment by MollyHoo** [comment]
> I am having the same issue. I'm using Windows 10, Visual Studio Code, Powershell to run the code. I already installed all those requirements successfully. I can also load deca_model.tar However, I got an error message regarding the compiler version... I wonder why? Could anyone help with that? Many thanks!
> 
> ```
> creating the FLAME Decoder
> trained model found. load D:\Research\Face Reconstruction\DECA\DECA\data\deca_model.tar
> C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
>   warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
> INFO: Could not find files for the given pattern(s).
> Traceback (most recent call last):
>   File "demos/demo_reconstruct.py", line 127, in <module>
>     main(parser.parse_args())
>   File "demos/demo_reconstruct.py", line 46, in main
>     deca = DECA(config = deca_cfg, device=device)
>   File "D:\Research\Face Reconstruction\DECA\DECA\decalib\deca.py", line 50, in __init__
>     self._setup_renderer(self.cfg.model)
>   File "D:\Research\Face Reconstruction\DECA\DECA\decalib\deca.py", line 53, in _setup_renderer
>     set_rasterizer(self.cfg.rasterizer_type)
>   File "D:\Research\Face Reconstruction\DECA\DECA\decalib\utils\renderer.py", line 41, in set_rasterizer
>     extra_cuda_cflags = ['-std=c++14', '-ccbin=$$(which gcc-7)']) # cuda10.2 is not compatible with gcc9. Specify gcc 7
>   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 974, in load
>     keep_intermediates=keep_intermediates)
>   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1179, in _jit_compile 
>     with_cuda=with_cuda)
>   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1272, in _write_ninja_file_and_build_library
>     with_cuda=with_cuda)
>   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1645, in _write_ninja_file_to_build_library
>     with_cuda=with_cuda)
>   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1747, in _write_ninja_file
>     'cl']).decode().split('\r\n')
>   File "C:\Users\Beibei\.conda\envs\py36\lib\subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "C:\Users\Beibei\.conda\envs\py36\lib\subprocess.py", line 438, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
> ```

same question. do you solve it?

**Comment by num-doc** [comment]
same question. do you solve it?
creating the FLAME Decoder
trained model found. load E:\objectPy\DECA-master\data\deca_model.tar

**Comment by HDYYZDN** [comment]
你找到standard_rasterize_cuda文件夹，然后删除lock文件，是锁住了，就可以解决了

**Comment by HDYYZDN** [comment]
> 你找到standard_rasterize_cuda文件夹，然后删除lock文件，是锁住了，就可以解决了

**Comment by HDYYZDN** [comment]
> 我的终端在加载给定deca_model时挂起。deca.py 行 88。我认为它没有处理任何任务。 有没有人发生过这种情况？如果您有任何解决方案，请告诉我。`trained model found. load D:\gitdoc\DECA\data\deca_model.tar`

你找到standard_rasterize_cuda文件夹，然后删除lock文件，是锁住了，就可以解决了

**Comment by HDYYZDN** [comment]
> > 我遇到了同样的问题。我正在使用 Windows 10、可视化工作室代码、强力外壳来运行代码。我已经成功安装了所有这些要求。我也可以加载deca_model.tar但是，我收到了有关编译器版本的错误消息...我想知道为什么？任何人都可以帮忙吗？非常感谢！
> > ```
> > creating the FLAME Decoder
> > trained model found. load D:\Research\Face Reconstruction\DECA\DECA\data\deca_model.tar
> > C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
> >   warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
> > INFO: Could not find files for the given pattern(s).
> > Traceback (most recent call last):
> >   File "demos/demo_reconstruct.py", line 127, in <module>
> >     main(parser.parse_args())
> >   File "demos/demo_reconstruct.py", line 46, in main
> >     deca = DECA(config = deca_cfg, device=device)
> >   File "D:\Research\Face Reconstruction\DECA\DECA\decalib\deca.py", line 50, in __init__
> >     self._setup_renderer(self.cfg.model)
> >   File "D:\Research\Face Reconstruction\DECA\DECA\decalib\deca.py", line 53, in _setup_renderer
> >     set_rasterizer(self.cfg.rasterizer_type)
> >   File "D:\Research\Face Reconstruction\DECA\DECA\decalib\utils\renderer.py", line 41, in set_rasterizer
> >     extra_cuda_cflags = ['-std=c++14', '-ccbin=$$(which gcc-7)']) # cuda10.2 is not compatible with gcc9. Specify gcc 7
> >   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 974, in load
> >     keep_intermediates=keep_intermediates)
> >   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1179, in _jit_compile 
> >     with_cuda=with_cuda)
> >   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1272, in _write_ninja_file_and_build_library
> >     with_cuda=with_cuda)
> >   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1645, in _write_ninja_file_to_build_library
> >     with_cuda=with_cuda)
> >   File "C:\Users\Beibei\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1747, in _write_ninja_file
> >     'cl']).decode().split('\r\n')
> >   File "C:\Users\Beibei\.conda\envs\py36\lib\subprocess.py", line 356, in check_output
> >     **kwargs).stdout
> >   File "C:\Users\Beibei\.conda\envs\py36\lib\subprocess.py", line 438, in run
> >     output=stdout, stderr=stderr)
> > subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
> > ```
> 
> 同样的问题。你解决了吗？

你找到standard_rasterize_cuda文件夹，然后删除lock文件，是锁住了，就可以解决了

**Comment by Daksitha** [comment]
were you able to find a solution? I am also running on Windows 10.

**Comment by luomulo** [comment]
> > 我的终端在加载给定deca_model时挂起。deca.py 行 88。我认为它没有处理任何任务。 有没有人发生过这种情况？如果您有任何解决方案，请告诉我。`trained model found. load D:\gitdoc\DECA\data\deca_model.tar`
> 
> 你找到standard_rasterize_cuda文件夹，然后删除lock文件，是锁住了，就可以解决了

兄弟，天才
