### ISSUE TITLE
Texture on the Detailed Mesh

### ISSUE THREAD

**Issue by ashwath98** [YadiraF/DECA#99]
Hi, I was able to successfully set up your repo on colab (let me know if I should add it somewhere), and was wondering if there was a way to get the texture on the detailed mesh (right now the texture I'm getting is for the mesh with 5000 vertices? Is Tranferring Vertex Colors between the two meshes the only way?

**Comment by aksh98** [comment]
Hi Ashwath, It would be great if you could share the requirements.txt/ yml file for others to be able to reproduce the environment..

**Comment by bornfree** [comment]
I have the same problem. The detailed mesh is actually missing UV maps.

My virtualenv on `Python 3.9.9`:
```
Package           Version
----------------- ------------------
chumpy            0.70
face-alignment    1.3.5
fvcore            0.1.5.post20211023
imageio           2.13.5
iopath            0.1.9
kornia            0.6.2
llvmlite          0.38.0
networkx          2.6.3
ninja             1.10.2.3
numba             0.55.0
numpy             1.21.5
opencv-python     4.5.5.62
packaging         21.3
Pillow            9.0.0
pip               21.3.1
portalocker       2.3.2
pyparsing         3.0.6
pytorch3d         0.6.1
PyWavelets        1.2.0
PyYAML            5.1.1
scikit-image      0.19.1
scipy             1.7.3
setuptools        59.8.0
six               1.16.0
tabulate          0.8.9
termcolor         1.1.0
tifffile          2021.11.2
torch             1.9.0
torchvision       0.10.0
tqdm              4.62.3
typing_extensions 4.0.1
wheel             0.37.1
yacs              0.1.8
```

Also, I'm running on a CPU (MacOS) using `pytorch3d` rasterizer.

**Comment by zw20045500** [comment]
> Also, I'm running on a CPU (MacOS) using `pytorch3d` rasterizer.

@bornfree do you run in  CPU (MacOS) using `pytorch3d` rasterizer.   do you have the error like the follow
trained model found. load /Users/zhouwei/avatar/DECA/data/deca_model.tar
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 127, in <module>
    main(parser.parse_args())
  File "demos/demo_reconstruct.py", line 46, in main
    deca = DECA(config = deca_cfg, device=device)
  File "/Users/zhouwei/avatar/DECA/decalib/deca.py", line 50, in __init__
    self._setup_renderer(self.cfg.model)
  File "/Users/zhouwei/avatar/DECA/decalib/deca.py", line 53, in _setup_renderer
    set_rasterizer(self.cfg.rasterizer_type)
  File "/Users/zhouwei/avatar/DECA/decalib/utils/renderer.py", line 28, in set_rasterizer
    from pytorch3d.io import load_obj
  File "/Users/zhouwei/opt/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/io/__init__.py", line 8, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/Users/zhouwei/opt/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/io/obj_io.py", line 22, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/Users/zhouwei/opt/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/Users/zhouwei/opt/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/renderer/blending.py", line 11, in <module>
    from pytorch3d import _C
ImportError: dlopen(/Users/zhouwei/opt/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so, 2): Symbol not found: __Z11_THArgCheckPKciiiS0_z
  Referenced from: /Users/zhouwei/opt/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so
